{
    "name": "Ship Docking",
    "author": "Techno THT Gmbh",
    "website": "www.techno-tht.tech",
    "summary": "Ship for docking",
    "depends": ["ship_management"],
    "data": [
        "security/role.xml",
        "security/rule.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/cron/supplier_quote_email_cron.xml",
        "data/cron/docking_plan_cron.xml",
        "data/cron/inspection_event_cron.xml",
        "data/cron/job_quote_request_cron.xml",
        "data/cron/material_quote_request_cron.xml",
        "data/access_supplier_portal_mail_templates.xml",
        "views/menu.xml",
        "views/docking_plan.xml",
        "views/equipment_survey_group.xml",
        "views/material_group.xml",
        "views/equipment_survey_metadata.xml",
        "views/equipment_survey_data.xml",
        "views/maintenance_scope.xml",
        "views/job.xml",
        "views/supplier.xml",
        "views/maintenance_scope_report.xml",
        "views/job_quote.xml",
        "views/job_supplier_quote.xml",
        "views/material_survey_metadata.xml",
        "views/material_quote.xml",
        "views/material_supplier_quote.xml",
        "views/material_survey_data.xml",
        "views/expected_cost_report.xml",
        "views/material_quote_request.xml",
        "views/job_quote_request.xml",
        "views/inspection_event_metadata.xml",
        "views/inspection_event.xml",
        "views/contract.xml",
        "views/contract_payment_instalment.xml",
        "views/cost_settlement_report.xml",
        "views/job_final_cost_formula.xml",
        "views/job_final_cost_predefined_factor.xml",
        "views/job_quote_final_parameter_set.xml",
        "views/job_quote_expected_parameter_set.xml",
        "views/contract_history.xml",
        "views/factor_note_option.xml",
        "reports/report.xml",
        "reports/material_quote.xml",
        "reports/contract.xml",
        "views/template/supplier_quote_change_portal_mail_template.xml",
        "views/template/job_rfq_mail_templates.xml",
        "views/template/contract_template.xml",
    ],
    "application": True,
    "assets": {
        "web.assets_backend": [
            "docking/static/css/my_css.css",
        ],
    },
}
