UTILITIES_MATERIAL_QUOTE = "utilities.material.quote"
UTILITIES_JOB_QUOTE = "utilities.job.quote"

SUPPLIER = "group_ship_supplier"
TECHNICAL_EXPERT = "group_ship_technical_expert"


PENDING = "PENDING"
APPROVED = "APPROVED"
REJECTED = "REJECTED"

APPROVAL_STATES = [
    (APPROVED, "Approved"),
    (PENDING, "Pending"),
    (REJECTED, "Rejected"),
]

MATERIAL = "MATERIAL"
SPARE_PART = "SPARE_PART"
PAINT = "PAINT"

MATERIAL_TYPE = [
    (MATERIAL, "Material"),
    (SPARE_PART, "Spare part"),
    (PAINT, "Paint"),
]

MACHINERY = "MACHINERY"
BOONG = "BOONG"

DEPARTMENT_IN_CHARGE = [
    (MACHINERY, "Machinery"),
    (BOONG, "Boong"),
]

UNAPPROVED = "UNAPPROVED"
TODO = "TODO"
WORKING = "WORKING"
COMPLETED = "COMPLETED"
CONFIRMED = "CONFIRMED"


JOB_STATES = [
    (UNAPPROVED, "Unapproved"),
    (TODO, "Todo"),
    (WORKING, "Working"),
    (COMPLETED, "Completed"),
    (CONFIRMED, "Confirmed"),
]

APPROVAL_FLOW_TYPE_SURVEY = "survey-approval-flow"
APPROVAL_FLOW_TYPE_JOB_QUOTE = "job-quote-approval-flow"
APPROVAL_FLOW_TYPE_MATERIAL_QUOTE = "material-quote-approval-flow"
APPROVAL_FLOW_TYPE_EXPECTED_COST_REPORT = "expected-cost-report-approval-flow"
APPROVAL_FLOW_TYPE_SCOPE_REPORT = "maintenance-scope-report-approval-flow"
APPROVAL_FLOW_TYPE_CONTRACT = "contract-flow"
APPROVAL_FLOW_TYPE_PROPOSED_LIQUIDATION = "proposed-liquidation-flow"
APPROVAL_FLOW_TYPE_COST_SETTLEMENT_REPORT = "cost-settlement-report-flow"
APPROVAL_FLOW_TYPE_INSPECTION_PLAN = "inspection-plan-flow"
APPROVAL_FLOW_TYPE_TECHNICAL_INCIDENT = "technical-incident-flow"
APPROVAL_FLOW_TYPE_EXPIRED_MATERIAL_ENTITY_REPLACEMENT_PROPOSAL = (
    "expired-material-entity-replacement-proposal"
)


APPROVAL_FLOW_TYPES = [
    (APPROVAL_FLOW_TYPE_SURVEY, "Survey approval flow"),
    (APPROVAL_FLOW_TYPE_JOB_QUOTE, "Job quote approval flow"),
    (APPROVAL_FLOW_TYPE_MATERIAL_QUOTE, "Material/Paint quote approval flow"),
    (APPROVAL_FLOW_TYPE_EXPECTED_COST_REPORT, "Expected cost report approval flow"),
    (APPROVAL_FLOW_TYPE_SCOPE_REPORT, "Maintenance scope report approval flow"),
    (APPROVAL_FLOW_TYPE_CONTRACT, "Contract approval flow"),
    (APPROVAL_FLOW_TYPE_PROPOSED_LIQUIDATION, "Proposed liquidation approval flow"),
    (APPROVAL_FLOW_TYPE_COST_SETTLEMENT_REPORT, "Cost settlement report approval flow"),
    (APPROVAL_FLOW_TYPE_INSPECTION_PLAN, "Inspection plan approval flow"),
    (APPROVAL_FLOW_TYPE_TECHNICAL_INCIDENT, "Technical incident approval flow"),
    (
        APPROVAL_FLOW_TYPE_EXPIRED_MATERIAL_ENTITY_REPLACEMENT_PROPOSAL,
        "Expired material entity replacement proposal approval flow",
    ),
]

USER_FOR_NOTIFICATION = "USER_FOR_NOTIFICATION"
EXPECT_START_DATE = "EXPECT_START_DATE"
HTML_VALUE = "HTML_VALUE"

FIELD = "FIELD"
RELATION_FIELDS = "RELATION_FIELDS"
NOTIFICATION_FOR_USER = "NOTIFICATION_FOR_USER"
APPROVAL_REMINDER_NOTIFICATION = "APPROVAL_REMINDER_NOTIFICATION"
DEFAULT_TYPES = [
    (RELATION_FIELDS, "Relation fields"),
    (FIELD, "Field"),
    (NOTIFICATION_FOR_USER, "Notification for users"),
    (APPROVAL_REMINDER_NOTIFICATION, "Approval reminder notification"),
]

NOTIFICATION_FOR_APPROVED = "NOTIFICATION_FOR_APPROVED"
PREPARE_FOR_INSPECTION_PLAN = "PREPARE_FOR_INSPECTION_PLAN"
NEED_REAL_DATE_FOR_INSPECTION_PLAN = "NEED_REAL_DATE_FOR_INSPECTION_PLAN"
FILL_IN_START_DATE_IN_DOCKING_PLAN = "FILL_IN_START_DATE_IN_DOCKING_PLAN"
CHANGING_INSPECTION_DATE = "CHANGING_INSPECTION_DATE"
CONFIRM_INSPECTION_DATE = "CONFIRM_INSPECTION_DATE"
NOTI_DOCKING_PLAN_BEFORE_3_MONTHS = "NOTI_DOCKING_PLAN_BEFORE_3_MONTHS"
NOTI_DOCKING_PLAN_BEFORE_6_MONTHS = "NOTI_DOCKING_PLAN_BEFORE_6_MONTHS"

NOTIFICATION_TYPES = [
    (NOTIFICATION_FOR_APPROVED, NOTIFICATION_FOR_APPROVED),
    (PREPARE_FOR_INSPECTION_PLAN, PREPARE_FOR_INSPECTION_PLAN),
    (NEED_REAL_DATE_FOR_INSPECTION_PLAN, NEED_REAL_DATE_FOR_INSPECTION_PLAN),
    (FILL_IN_START_DATE_IN_DOCKING_PLAN, FILL_IN_START_DATE_IN_DOCKING_PLAN),
    (CHANGING_INSPECTION_DATE, CHANGING_INSPECTION_DATE),
    (NOTI_DOCKING_PLAN_BEFORE_3_MONTHS, NOTI_DOCKING_PLAN_BEFORE_3_MONTHS),
    (NOTI_DOCKING_PLAN_BEFORE_6_MONTHS, NOTI_DOCKING_PLAN_BEFORE_6_MONTHS),
]

STRING = "STRING"
INTEGER = "INTEGER"
FLOAT = "FLOAT"
DATE = "DATE"
HTML = "HTML"
USERS = "USERS"
GROUPS = "GROUPS"
RELATION = "RELATION"

VALUE_TYPES = [
    (STRING, "String"),
    (INTEGER, "Integer"),
    (FLOAT, "Float"),
    (DATE, "Date"),
    (HTML, "Html"),
    (USERS, "Users"),
    (GROUPS, "Groups"),
    (RELATION, "Relation"),
]

PAYMENT_STATUS = [
    (PENDING, "Pending"),
    (COMPLETED, "Completed"),
]

NORMAL = "NORMAL"
ARISE = "ARISE"

ARISE_SELECTION = [
    (NORMAL, "Normal"),
    (ARISE, "Arise"),
]

MINUTES = "minutes"
HOURS = "hours"
DAYS = "days"

INTERVAL_TYPE = [
    (MINUTES, "Minutes"),
    (HOURS, "Hours"),
    (DAYS, "Days"),
]

HTML_DOCKING_CONTRACT_UNRENDERED_CONTENT = "HTML_DOCKING.CONTRACT_UNRENDERED_CONTENT"
RELATION_SHIP_FUEL_EXTERNAL_RECEIVING_FUEL_CHECKS = (
    "RELATION_SHIP.FUEL.EXTERNAL.RECEIVING_FUEL_CHECKS"
)
RELATION_SHIP_FUEL_INTERNAL_RECEIVING_FUEL_CHECKS = (
    "RELATION_SHIP.FUEL.INTERNAL.RECEIVING_FUEL_CHECKS"
)
RELATION_SHIP_INTERNAL_AUDIT_CHECKLIST_CHECKLIST = (
    "RELATION_SHIP.INTERNAL.AUDIT.CHECKLIST_CHECKLIST"
)
RELATION_SHIP_INTERNAL_MLC_AUDIT_CHECKLIST_CHECKLIST = (
    "RELATION_SHIP.INTERNAL.MLC.AUDIT.CHECKLIST_CHECKLIST"
)

DATE_DOCKING_DOCKING_PLAN_EXPECTED_DATE = "DATE_DOCKING.DOCKING.PLAN_EXPECTED_DATE"
HTML_LEGIS_SAFETY_MANAGEMENT_HANDBOOK_CONTENT = (
    "HTML_LEGIS.SAFETY.MANAGEMENT.HANDBOOK_CONTENT"
)
INTEGER_SHIP_FUEL_CONSUMPTION_CURRENT_FO = "INTEGER_SHIP.FUEL_CONSUMPTION_CURRENT_FO"
INTEGER_SHIP_FUEL_CONSUMPTION_CURRENT_DO = "INTEGER_SHIP.FUEL_CONSUMPTION_CURRENT_DO"
HTML_SHIP_FUEL_EXTERNAL_RECEIVING_BUNKERING_SAFETY_CHECKLIST = (
    "HTML_SHIP.FUEL.EXTERNAL.RECEIVING_BUNKERING_SAFETY_CHECKLIST"
)
HTML_SHIP_FUEL_INTERNAL_RECEIVING_BUNKERING_SAFETY_CHECKLIST = (
    "HTML_SHIP.FUEL.INTERNAL.RECEIVING_BUNKERING_SAFETY_CHECKLIST"
)
INTEGER_SHIP_INSPECTION_PLAN_GENERAL_PRENOTI_DAYS = (
    "INTEGER_SHIP.INSPECTION.PLAN_GENERAL_PRENOTI_DAYS"
)
INTEGER_SHIP_INSPECTION_PLAN_SPECIALLIST_PRENOTI_DAYS = (
    "INTEGER_SHIP.INSPECTION.PLAN_SPECIALLIST_PRENOTI_DAYS"
)
INTEGER_SHIP_JOB_QUOTE_TEMPLATE_DEADLINE_DAY_COUNT = (
    "INTEGER_SHIP.JOB.QUOTE.TEMPLATE_DEADLINE_DAY_COUNT"
)
INTEGER_SHIP_JOB_QUOTE_TEMPLATE_DAY_COUNT_VALID_FOT_EDITING_IMPLEMENT_DATE = (
    "INTEGER_SHIP.JOB.QUOTE.TEMPLATE_DAY_COUNT_VALID_FOT_EDITING_IMPLEMENT_DATE"
)
INTEGER_SHIP_MAINTENANCE_SCOPE_REPORT_TEMPLATE_DEADLINE_DAY_COUNT = (
    "INTEGER_SHIP.MAINTENANCE.SCOPE.REPORT.TEMPLATE_DEADLINE_DAY_COUNT"
)
INTEGER_SHIP_MATERIAL_PAINT_QUOTES_REQUEST_DEADLINE_DAY_COUNT = (
    "INTEGER_SHIP.MATERIAL.PAINT.QUOTES.REQUEST_DEADLINE_DAY_COUNT"
)
HTML_EXPORT_REPORT_WIZ_RENDERED_MEDICINE_CONTENT = (
    "HTML_EXPORT.REPORT.WIZ_RENDERED_MEDICINE_CONTENT"
)
USERS_DOCKING_DOCKING_PLAN_FILL_IN_START_DATE = (
    "USERS_DOCKING.DOCKING.PLAN_FILL_IN_START_DATE"
)
USERS_DOCKING_DOCKING_PLAN_NOTI_BEFORE_3_MONTHS = (
    "USERS_DOCKING.DOCKING.PLAN_NOTI_BEFORE_3_MONTHS"
)
USERS_DOCKING_DOCKING_PLAN_NOTI_BEFORE_6_MONTHS = (
    "USERS_DOCKING.DOCKING.PLAN_NOTI_BEFORE_6_MONTHS"
)
USERS_DOCKING_INSPECTION_EVENT_CONFIRM_INSPECTION_DATE = (
    "USERS_DOCKING.INSPECTION.EVENT_CONFIRM_INSPECTION_DATE"
)
USERS_SHIP_INSPECTION_PLAN_NEED_PREPARE = "USERS_SHIP.INSPECTION.PLAN_NEED_PREPARE"
USERS_LEGIS_EDITING_REQUEST_FOR_HANDBOOK_PERIODIC_NOTIFY = (
    "USERS_LEGIS.EDITING.REQUEST.FOR.HANDBOOK_PERIODIC_NOTIFY"
)
USERS_SHIP_INSPECTION_PLAN_NEED_REAL_DATE = "USERS_SHIP.INSPECTION.PLAN_NEED_REAL_DATE"
USERS_UTILITIES_APPROVAL_STATUS_NOTIFICATION_FOR_APPROVED = (
    "USERS_UTILITIES.APPROVAL.STATUS_NOTIFICATION_FOR_APPROVED"
)
INTEGER_UTILITIES_APPROVAL_STATUS_INTERVAL_NUMBER_TIME_FOR_APPROVER = (
    "INTEGER_UTILITIES.APPROVAL.STATUS_INTERVAL_NUMBER_TIME_FOR_APPROVER"
)
STRING_UTILITIES_APPROVAL_STATUS_INTERVAL_TYPE_TIME_FOR_APPROVER = (
    "STRING_UTILITIES.APPROVAL.STATUS_INTERVAL_TYPE_TIME_FOR_APPROVER"
)
USERS_DOCKING_INSPECTION_EVENT_CHANGING_INSPECTION_DATE = (
    "USERS_DOCKING.INSPECTION.EVENT_CHANGING_INSPECTION_DATE"
)
INTEGER_SHIP_FUEL_DAY_OF_THE_MONTH = "INTEGER_SHIP.FUEL_DAY_OF_THE_MONTH"
GROUPS_SHIP_JOB_QUOTE_TEMPLATE_CHANGING_CONFIRM_JOB_STATE = (
    "GROUPS_SHIP.JOB.QUOTE.TEMPLATE_CHANGING_CONFIRM_JOB_STATE"
)
HTML_LEGIS_REQUISITION_FOR_HANDBOOK_REVISION = (
    "HTML_LEGIS.REQUISITION.FOR.HANDBOOK.REVISION"
)

DEFAULT_VALUE_VARIABLE_NAMES = [
    (
        STRING_UTILITIES_APPROVAL_STATUS_INTERVAL_TYPE_TIME_FOR_APPROVER,
        STRING_UTILITIES_APPROVAL_STATUS_INTERVAL_TYPE_TIME_FOR_APPROVER,
    ),
    (
        INTEGER_SHIP_FUEL_CONSUMPTION_CURRENT_FO,
        INTEGER_SHIP_FUEL_CONSUMPTION_CURRENT_FO,
    ),
    (
        INTEGER_SHIP_FUEL_CONSUMPTION_CURRENT_DO,
        INTEGER_SHIP_FUEL_CONSUMPTION_CURRENT_DO,
    ),
    (
        INTEGER_SHIP_INSPECTION_PLAN_GENERAL_PRENOTI_DAYS,
        INTEGER_SHIP_INSPECTION_PLAN_GENERAL_PRENOTI_DAYS,
    ),
    (
        INTEGER_SHIP_INSPECTION_PLAN_SPECIALLIST_PRENOTI_DAYS,
        INTEGER_SHIP_INSPECTION_PLAN_SPECIALLIST_PRENOTI_DAYS,
    ),
    (
        INTEGER_SHIP_JOB_QUOTE_TEMPLATE_DEADLINE_DAY_COUNT,
        INTEGER_SHIP_JOB_QUOTE_TEMPLATE_DEADLINE_DAY_COUNT,
    ),
    (
        INTEGER_SHIP_JOB_QUOTE_TEMPLATE_DAY_COUNT_VALID_FOT_EDITING_IMPLEMENT_DATE,
        INTEGER_SHIP_JOB_QUOTE_TEMPLATE_DAY_COUNT_VALID_FOT_EDITING_IMPLEMENT_DATE,
    ),
    (
        INTEGER_SHIP_MAINTENANCE_SCOPE_REPORT_TEMPLATE_DEADLINE_DAY_COUNT,
        INTEGER_SHIP_MAINTENANCE_SCOPE_REPORT_TEMPLATE_DEADLINE_DAY_COUNT,
    ),
    (
        INTEGER_SHIP_MATERIAL_PAINT_QUOTES_REQUEST_DEADLINE_DAY_COUNT,
        INTEGER_SHIP_MATERIAL_PAINT_QUOTES_REQUEST_DEADLINE_DAY_COUNT,
    ),
    (
        INTEGER_UTILITIES_APPROVAL_STATUS_INTERVAL_NUMBER_TIME_FOR_APPROVER,
        INTEGER_UTILITIES_APPROVAL_STATUS_INTERVAL_NUMBER_TIME_FOR_APPROVER,
    ),
    (INTEGER_SHIP_FUEL_DAY_OF_THE_MONTH, INTEGER_SHIP_FUEL_DAY_OF_THE_MONTH),
    (DATE_DOCKING_DOCKING_PLAN_EXPECTED_DATE, DATE_DOCKING_DOCKING_PLAN_EXPECTED_DATE),
    (
        HTML_DOCKING_CONTRACT_UNRENDERED_CONTENT,
        HTML_DOCKING_CONTRACT_UNRENDERED_CONTENT,
    ),
    (
        HTML_SHIP_FUEL_EXTERNAL_RECEIVING_BUNKERING_SAFETY_CHECKLIST,
        HTML_SHIP_FUEL_EXTERNAL_RECEIVING_BUNKERING_SAFETY_CHECKLIST,
    ),
    (
        HTML_LEGIS_SAFETY_MANAGEMENT_HANDBOOK_CONTENT,
        HTML_LEGIS_SAFETY_MANAGEMENT_HANDBOOK_CONTENT,
    ),
    (
        HTML_EXPORT_REPORT_WIZ_RENDERED_MEDICINE_CONTENT,
        HTML_EXPORT_REPORT_WIZ_RENDERED_MEDICINE_CONTENT,
    ),
    (
        HTML_SHIP_FUEL_INTERNAL_RECEIVING_BUNKERING_SAFETY_CHECKLIST,
        HTML_SHIP_FUEL_INTERNAL_RECEIVING_BUNKERING_SAFETY_CHECKLIST,
    ),
    (
        HTML_LEGIS_REQUISITION_FOR_HANDBOOK_REVISION,
        HTML_LEGIS_REQUISITION_FOR_HANDBOOK_REVISION,
    ),
    (
        USERS_DOCKING_DOCKING_PLAN_FILL_IN_START_DATE,
        USERS_DOCKING_DOCKING_PLAN_FILL_IN_START_DATE,
    ),
    (
        USERS_DOCKING_DOCKING_PLAN_NOTI_BEFORE_3_MONTHS,
        USERS_DOCKING_DOCKING_PLAN_NOTI_BEFORE_3_MONTHS,
    ),
    (
        USERS_DOCKING_DOCKING_PLAN_NOTI_BEFORE_6_MONTHS,
        USERS_DOCKING_DOCKING_PLAN_NOTI_BEFORE_6_MONTHS,
    ),
    (
        USERS_DOCKING_INSPECTION_EVENT_CONFIRM_INSPECTION_DATE,
        USERS_DOCKING_INSPECTION_EVENT_CONFIRM_INSPECTION_DATE,
    ),
    (USERS_SHIP_INSPECTION_PLAN_NEED_PREPARE, USERS_SHIP_INSPECTION_PLAN_NEED_PREPARE),
    (
        USERS_SHIP_INSPECTION_PLAN_NEED_REAL_DATE,
        USERS_SHIP_INSPECTION_PLAN_NEED_REAL_DATE,
    ),
    (
        USERS_UTILITIES_APPROVAL_STATUS_NOTIFICATION_FOR_APPROVED,
        USERS_UTILITIES_APPROVAL_STATUS_NOTIFICATION_FOR_APPROVED,
    ),
    (
        USERS_DOCKING_INSPECTION_EVENT_CHANGING_INSPECTION_DATE,
        USERS_DOCKING_INSPECTION_EVENT_CHANGING_INSPECTION_DATE,
    ),
    (
        USERS_LEGIS_EDITING_REQUEST_FOR_HANDBOOK_PERIODIC_NOTIFY,
        USERS_LEGIS_EDITING_REQUEST_FOR_HANDBOOK_PERIODIC_NOTIFY,
    ),
    (
        GROUPS_SHIP_JOB_QUOTE_TEMPLATE_CHANGING_CONFIRM_JOB_STATE,
        GROUPS_SHIP_JOB_QUOTE_TEMPLATE_CHANGING_CONFIRM_JOB_STATE,
    ),
    (
        RELATION_SHIP_FUEL_INTERNAL_RECEIVING_FUEL_CHECKS,
        RELATION_SHIP_FUEL_INTERNAL_RECEIVING_FUEL_CHECKS,
    ),
    (
        RELATION_SHIP_FUEL_EXTERNAL_RECEIVING_FUEL_CHECKS,
        RELATION_SHIP_FUEL_EXTERNAL_RECEIVING_FUEL_CHECKS,
    ),
    (
        RELATION_SHIP_INTERNAL_AUDIT_CHECKLIST_CHECKLIST,
        RELATION_SHIP_INTERNAL_AUDIT_CHECKLIST_CHECKLIST,
    ),
    (
        RELATION_SHIP_INTERNAL_MLC_AUDIT_CHECKLIST_CHECKLIST,
        RELATION_SHIP_INTERNAL_MLC_AUDIT_CHECKLIST_CHECKLIST,
    ),
]

SECOND_TIME_APPROVAL_OPTION_VALUE = "SECOND_TIME_APPROVAL_OPTION_VALUE"
