apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchart.fullname" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.service.longpollingEnabled }}
    - port: {{ .Values.service.longpollingPort }}
      targetPort: longpolling
      protocol: TCP
      name: longpolling
  {{- end }}
  selector:
    {{- include "helmchart.selectorLabels" . | nindent 4 }}
