{
    "name": "Ship safety legislation",
    "author": "Techno THT Gmbh",
    "website": "www.techno-tht.tech",
    "summary": "Ship safety legislation",
    "depends": ["ship_management"],
    "data": [
        "security/rule.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/editing_request_for_handbook_cron.xml",
        "views/menu.xml",
        "views/technical_incident.xml",
        "views/technical_incident_job.xml",
        "views/technical_incident_insurance.xml",
        "views/safety_management_handbook.xml",
        "views/handbook_section.xml",
        "views/ert_role_task_meta.xml",
        "views/ert_role_meta.xml",
        "views/incidence_type_meta.xml",
        "views/serious_accident.xml",
        "views/serious_accident_team.xml",
        "views/serious_accident_task.xml",
        "views/editing_request_for_handbook.xml",
        "views/changed_content_of_handbook.xml",
        "views/meta_form.xml",
        "views/content_page.xml",
        "views/accident_report.xml",
        "views/investigative_report.xml",
        "views/sea_protest.xml",
        "views/team_checklist.xml",
        "views/technical_incident_report.xml",
        "views/serious_accident_report.xml",
        "views/handbook_revision_report.xml",
        "views/requisition_for_handbook_revision.xml",
        "reports/report.xml",
        "reports/technical_incident_report.xml",
        "reports/accident_report_pdf.xml",
        "reports/investigative_report_pdf.xml",
        "reports/sea_protest_report.xml",
        "reports/team_checklist_pdf.xml",
        "reports/requisition_for_handbook_revision.xml",
        "reports/handbook_revision_report.xml",
    ],
    "application": True,
    "assets": {
        "web.assets_backend": [
            "safety_legislation/static/css/my_css.css",
            "safety_legislation/static/css/odoo.css",
        ],
    },
}
